//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_System.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;
    

    public partial class Person
    {
        public int PersonId { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        [StringLength(200, MinimumLength = 3)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        [StringLength(200, MinimumLength = 3)]
        public string LastName { get; set; }

        public System.DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = "Status is required")]
        public int StatusId { get; set; }

        [Required(ErrorMessage = "Departmewnt is required")]
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CompanyId { get; set; }

        [Required(ErrorMessage = "Employee Number is required")]
        public string EmployeeNumber { get; set; }

        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Status Status { get; set; }
    }
}
